# Generated by Django 4.2.4 on 2024-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=15)),
                ("faceimage", models.ImageField(upload_to="face_images/")),
                ("face_encode", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
