# Generated by Django 4.2.4 on 2024-07-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashier",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                (
                    "photo_profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="cashier_profiles/"
                    ),
                ),
            ],
        ),
    ]
