# Generated by Django 4.2.4 on 2024-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecog", "0002_cashier"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashier",
            name="role",
            field=models.CharField(
                choices=[("cashier", "Cashier"), ("manager", "Manager")],
                default="cashier",
                max_length=10,
            ),
        ),
    ]
